### Topics

- List comprehensions and the basics of generator expressions
- Using tuples as records versus using tuples as immutable lists
- Sequence unpacking and sequence patterns
- Reading from slices and writing to slices
- Specialized sequence types, like arrays and queues

#### Container sequences

- Can hold items of different types, including nested containers
    - list
    - tuple 
    - deque
    
- A container sequence holds references to the objects it contains, which may be of any type
    
#### Flat sequences

- Hold items of one simple type
    - str
    - bytes
    - array
    
- A flat sequence stores the value of its contents in its own memory space not as distinct Python objects

<img src="fig2.1.png" alt="Alternative text" />

Every Python object in memory has a header with metadata. A float, has a value field and two metadata fields:

- ob_refcnt: the object’s reference count
- ob_type: a pointer to the object’s type
- ob_fval: a C double holding the value of the float

#### Note: On a 64-bit Python build, each of those fields takes 8 bytes. Array of floats is much more compact than a tuple of floats

##### Another way of grouping sequence types is by mutability:

- Mutable sequences
    - list
    - bytearray
    - array
    - deque

- Immutable sequences
    - tuple
    - str
    - bytes

#### List Comprehensions

In [1]:
symbols = '$¢£¥€¤'
codes = []
for symbol in symbols:
    codes.append(ord(symbol))

codes

[36, 162, 163, 165, 8364, 164]

In [2]:
symbols = '$¢£¥€¤'
codes = [ord(symbol) for symbol in symbols]
codes

[36, 162, 163, 165, 8364, 164]

##### Cartesian Products

In [4]:
h = ['x1', 'x2', 'x3']
v = ['y1', 'y2', 'y3']

p = [(h_i, v_i) for h_i in h
                for v_i in v]

p

[('x1', 'y1'),
 ('x1', 'y2'),
 ('x1', 'y3'),
 ('x2', 'y1'),
 ('x2', 'y2'),
 ('x2', 'y3'),
 ('x3', 'y1'),
 ('x3', 'y2'),
 ('x3', 'y3')]

#### Generator Expressions

- yields items one by one using the iterator protocol instead of building a whole list
- Genexps use the same syntax as listcomps, but are enclosed in parentheses rather than brackets

In [8]:
h = ['x1', 'x2', 'x3']
v = ['y1', 'y2', 'y3']

for item in ((h_i, v_i) for h_i in h
                        for v_i in v):
    print(item)

('x1', 'y1')
('x1', 'y2')
('x1', 'y3')
('x2', 'y1')
('x2', 'y2')
('x2', 'y3')
('x3', 'y1')
('x3', 'y2')
('x3', 'y3')


#### Tuples Are Not Just Immutable Lists

##### Tuples as Records

Sorting the tuple would destroy the information because the meaning of each field is given by its position in the tuple.

In [9]:
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)

##### Tuples as Immutable Lists

- When you see a tuple in code, you know its length will never change
- A tuple uses less memory than a list of the same length, and it allows Python to do some optimizations


#### Note: The immutability of a tuple only applies to the references contained in it. References in a tuple cannot be deleted or replaced. But if one of those references points to a mutable object, and that object is changed, then the value of the tuple changes.

In [11]:
a = (10, 'alpha', [1, 2])
b = (10, 'alpha', [1, 2])
print(f'b: {b}')

print(f'before: {a == b}')

b[-1].append(99)
print(f'after: {a == b}')

print(f'b: {b}')

b: (10, 'alpha', [1, 2])
before: True
after: False
b: (10, 'alpha', [1, 2, 99])


#### If you want to determine explicitly if a tuple (or any object) has a fixed value, you can use the hash built-in

In [12]:
hash((10, 'alpha', (1, 2)))

-2975815331967661896

In [13]:
hash((10, 'alpha', [1, 2]))

TypeError: unhashable type: 'list'

In [14]:
def fixed(o):
    try:
        hash(o)
    except TypeError:
        return False
    return True

In [15]:
fixed((10, 'alpha', (1, 2)))

True

In [16]:
fixed((10, 'alpha', [1, 2]))

False

#### Unpacking Sequences and Iterables

In [17]:
city, year, pop, chg, area = ('Tokyo', 2003, 32_450, 0.66, 8014)

##### Using * to Grab Excess Items
##### Using _ as dummy variable

In [18]:
city, *_ = ('Tokyo', 2003, 32_450, 0.66, 8014)
city

'Tokyo'

##### Unpacking with * in Function Calls and Sequence Literals

In [19]:
def fun(a, b, c, d, *rest):
    return a, b, c, d, rest

In [20]:
fun(*[1, 2], 3, *range(4, 7))

(1, 2, 3, 4, (5, 6))

In [21]:
a, b, c, d, *rest = *[1, 2], 3, *range(4, 7)

In [22]:
a, b, c, d, *rest

(1, 2, 3, 4, 5, 6)

In [26]:
print(*[1, 2])

1 2


In [27]:
print([1, 2])

[1, 2]


#### Pattern Matching with Sequences

- match/case statement (Since Python 3.10)

In [42]:
def number_to_string(argument):
    match argument:
        case a, b, c:
            return a, b, c
        case a, b, c, d:
            return a, b, c, d
        case a, b, *extra:
            return a, b
        case default:
            return None

In [43]:
number_to_string((1, 2, 3))

(1, 2, 3)

In [44]:
number_to_string((1, 2, 3, 4))

(1, 2, 3, 4)

In [45]:
number_to_string((1, 2, 3, 4, 5))

(1, 2)

In [46]:
number_to_string(())

In [47]:
a, b = (1, 2, 3, 4)

ValueError: too many values to unpack (expected 2)

In [51]:
a, *b = (1, 2, 3, 4)
a, b

(1, [2, 3, 4])

In [55]:
a, *b = (1, 2, 3, 4)
a, *b

(1, 2, 3, 4)

In [53]:
(a, *b) = (1, 2, 3, 4)
a, b

(1, [2, 3, 4])

In [54]:
a, *b = 1, 2, 3, 4
a, b

(1, [2, 3, 4])

#### match/case with if

In [56]:
def number_to_string(argument):
    match argument:
        case a, b, c if a == 1:
            return a, b, c
        case a, b, c, d:
            return a, b, c, d
        case a, b, *extra:
            return a, b
        case default:
            return None

In [57]:
number_to_string((1, 2, 3))

(1, 2, 3)

In [58]:
number_to_string((2, 2, 3))

(2, 2)

#### binding

In [59]:
def number_to_string(argument):
    match argument:
        case a, b, c as res:
            return res
        case a, b, c, d:
            return a, b, c, d
        case a, b, *extra:
            return a, b
        case default:
            return None

In [60]:
number_to_string((1, 2, 3))

3

In [70]:
def number_to_string(argument):
    match argument:
        case (a, b, c) as res:
            return res
        case a, b, c, d:
            return a, b, c, d
        case a, b, *extra:
            return a, b
        case default:
            return None

In [71]:
number_to_string((1, 2, 3))

(1, 2, 3)

#### adding type information

In [72]:
def number_to_string(argument):
    match argument:
        case a, b, int(c) as res:
            return res
        case a, b, c, d:
            return a, b, c, d
        case a, b, *extra:
            return a, b
        case default:
            return None

In [73]:
number_to_string((1, 2, 3))

3

In [74]:
number_to_string((1, 2, 3.1))

(1, 2)

#### Slicing

- all sequence types in Python support slicing operations

##### seq[start:stop:step]

##### seq.\_\_getitem\_\_(slice(start, stop, step))

In [12]:
s = (1, 2, 3, 4, 5)

print(s[0:5:1])
print(s.__getitem__((slice(0, 5, 1))))

print(s[(slice(0, 5, 1))])
print(s[slice(0, 5, 1)])

(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)
(1, 2, 3, 4, 5)


#### Using + and * with Sequences

- Both + and * always create a new object, and never change their operands

In [20]:
a = [1, 2, 3]
print(id(a))
b = [4, 5, 6]
a = a + b
print(a)
print(id(a))

2666984565568
[1, 2, 3, 4, 5, 6]
2666984564480


In [21]:
a = [1, 2, 3]
print(id(a))
b = [4, 5, 6]
a += b
print(a)
print(id(a))

2666984442688
[1, 2, 3, 4, 5, 6]
2666984442688


In [25]:
a = [1, 2, 3]
print(id(a))
a = a*2
print(a)
print(id(a))

2666963214528
[1, 2, 3, 1, 2, 3]
2666962183232


In [27]:
a = [1, 2, 3]
print(id(a))
a *= 2
print(a)
print(id(a))

2666984721216
[1, 2, 3, 1, 2, 3]
2666984721216


####   += and *= are translates to \_\_iadd\_\_ and \_\_imul\_\_

#### list.sort Versus the sorted Built-In

- list.sort method sorts a list in place. It returns None.

- the built-in function sorted creates a new list and returns it.

- Both list.sort and sorted take two optional, keyword-only arguments:
    - reverse 
        - If True, the items are returned in descending order (i.e., by reversing the comparison of the items). The default is False.
    - key
        - A one-argument function that will be applied to each item to produce its sorting key.

In [29]:
print(['fruits', 'books', 'rivers'].sort())

None


In [30]:
print(sorted(['fruits', 'books', 'rivers']))

['books', 'fruits', 'rivers']


In [41]:
def get_age(item):
    return item[2]

print(sorted([
                ('john', 'A', 15),
                ('jane', 'B', 12),
                ('dave', 'B', 10),
            ], key=get_age))

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]


In [43]:
print(sorted([
                ('john', 'A', 15),
                ('jane', 'B', 12),
                ('dave', 'B', 10),
            ], key=lambda item: item[2]))

[('dave', 'B', 10), ('jane', 'B', 12), ('john', 'A', 15)]


#### Arrays

- If a list only contains numbers, an array.array is a more efficient replacement.

In [9]:
from array import array
import sys

In [7]:
%%timeit
array('d', (i for i in range(10**3)))

198 µs ± 43.7 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
sys.getsizeof(array('d', (i for i in range(10**3))))

8320

In [8]:
%%timeit
list((i for i in range(10**3)))

74.6 µs ± 6.39 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [11]:
sys.getsizeof(list((i for i in range(10**3))))

8856

#### Memory Views

- The built-in memoryview class is a shared-memory sequence type that lets you handle slices of arrays without copying bytes.

In [12]:
octets = array('B', range(6))

In [13]:
m1 = memoryview(octets)

In [14]:
m1.tolist()

[0, 1, 2, 3, 4, 5]

In [15]:
m2 = m1.cast('B', [2, 3])

In [16]:
m2.tolist()

[[0, 1, 2], [3, 4, 5]]

In [17]:
m3 = m1.cast('B', [3, 2])

In [18]:
m3.tolist()

[[0, 1], [2, 3], [4, 5]]

In [19]:
m2[1,1] = 22

In [20]:
m3[1,1] = 33

In [22]:
octets

array('B', [0, 1, 2, 33, 22, 5])

#### NumPy

- for advanced array and matrix operations
- for scientific computing algorithms - linear algebra, numerical calculus, and statistics

In [26]:
import numpy as np

In [27]:
a = np.arange(12)

In [28]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
a.shape = 3, 4

In [30]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

#### Deques and Other Queues

- with .append and .pop(0) on a list, you get FIFO behavior, but it is costly because the entire list must be shifted in memory

- The class collections.deque is a thread-safe double-ended queue designed for fast inserting and removing from both ends. Possible use case - list of "n last seen items"

In [32]:
from collections import deque

In [33]:
dq = deque(range(10), maxlen=10)

In [34]:
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [35]:
dq.appendleft(-1)

In [36]:
dq

deque([-1, 0, 1, 2, 3, 4, 5, 6, 7, 8], maxlen=10)

In [37]:
dq.extend([11, 22, 33])

In [38]:
dq

deque([2, 3, 4, 5, 6, 7, 8, 11, 22, 33], maxlen=10)

#### Besides deque, other Python standard library packages implement queues

- queue
    - SimpleQueue (bounded by a max size argument, when the queue is full, the insertion of a new item blocks until removed by another thread - can be used for throttling)
    - Queue
    - LifoQueue
    - PriorityQueue
    
- multiprocessing (inter-process communication)
    - SimpleQueue
    - Queue
    
- asyncio (asynchronous programming)
    - Queue
    - LifoQueue
    - PriorityQueue
    - JoinableQueue
    
- heapq (heap queue or priority queue)